name: Sync Developing → Testing

on:
  push:
    branches:
      - developing

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Merge to Testing
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@bmp.com"

          git fetch origin
          git checkout testing

          git merge origin/developing --no-edit

          git push origin testing
